#Spring.Data.Mongo.Host = LocalHost          # Needed to identify who is hosting
#Spring.Data.Mongo.Port = 27017              # Needed to identify on what port it is being hosted

#Spring.data.mongodb.uri = spring.data.mongodb.uri=mongodb+srv://afaqalam323_db_user:lUeeMzTU1IsX7ulZ@cluster0.vzemmp8.mongodb.net/journal?appName=Cluster0       # Needed to identify who is hosting, its mongo atlas
##spring.data.mongodb.database= journal    # Needed to identify onto what DB we are referring to
#Spring.Data.Mongo.username = Ezio
#Spring.Data.Mongo.Password = 123

#spring.data.mongodb.uri=mongodb+srv://afaqalam323_db_user:lUeeMzTU1IsX7ulZ@cluster0.vzemmp8.mongodb.net/journal?appName=Cluster0
#spring.data.mongodb.auto-index-creation=true